on:
  push:
    branches:
      - '*backend*'
      - main
      - '*frontend*'

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || contains(github.ref_name, 'backend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

  build-and-push-frontend:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || contains(github.ref_name, 'frontend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install